version: "0.1"

services:
  web:
    image: ghcr.io/carlosfranzreb/boulders:latest
    build: .
    command: python run.py
    volumes:
      - ./climbz/:/usr/src/climbz
      - ./instance:/usr/src/instance
    ports:
      - 5000:5000
      - 5670:5670
    env_file:
      - ./.env
    entrypoint: [
      "python",
      "-m",
      "debugpy",
      "--listen",
      "0.0.0.0:5670",
      "run.py",
    ]