services:
  web:
    image: ghcr.io/carlosfranzreb/boulders:latest
    build: .
    volumes:
      - ./myclimbz/:/usr/src/myclimbz
      - ./instance:/usr/src/instance
      - ./gunicorn_socket:/usr/src/gunicorn_socket
      - ./videos/:/usr/src/videos
    env_file:
      - .env
    ports:
      - 5000:5000
      - 5670:5670