version: "0.1"

services:
  web:
    image: ghcr.io/carlosfranzreb/boulders:latest
    build: .
    volumes:
      - ./climbz/:/usr/src/climbz
      - ./instance:/usr/src/instance
      - ./gunicorn_socket:/usr/src/gunicorn_socket
    env_file:
      - .env
    ports:
      - 5000:5000
      - 5670:5670