# For this to work, the last commit message must contain the version number in the
# format "Version: x.y.z"

name: "Tag release and deploy to production server"
on:
  push:
    branches:
      - main
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: christophebedard/tag-version-commit@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version_regex: 'Version: ([0-9]+\.[0-9]+\.[0-9]+)'
          version_tag_prefix: "v"
          check_entire_commit_message: true
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Push code to production server
        run: |
          echo ${{ secrets.HETZNER_KEY }} > ~/hetzner_key.pub
          ssh -i ~/hetzner_key.pub ${{ secrets.HETZNER_USER }}@${{ secrets.HETZNER_HOST }} "cd /root/boulders && bash scripts/deploy.sh"
