# For this to work, the last commit message must contain the version number in the
# format "Version: x.y.z"

name: "Tag release and deploy to production server"
on:
  push:
    branches:
      - main
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: christophebedard/tag-version-commit@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version_regex: 'Version: ([0-9]+\.[0-9]+\.[0-9]+)'
          version_tag_prefix: "v"
          check_entire_commit_message: true
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USER }}
          key: ${{ secrets.HETZNER_KEY }}
          # port: 432
          script: cd /root/boulders && bash scripts/deploy.sh
