name: Create, publish and test a Docker image

on:
    pull_request:
        branches:
            - main

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: carlosfranzreb/boulders/myclimbz

jobs:
    build-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Log in to the Container registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}

    test:
        runs-on: ubuntu-latest
        needs: build-push
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Restart app after checkout
              uses: docker://docker
              with:
                  args: docker restart app

            - name: Update pip
              run: python -m pip install --upgrade pip

            - name: Install app dependencies
              run: pip install -r requirements.txt

            - name: Install ChromeDriver
              uses: nanasess/setup-chromedriver@v2

            - name: Install dependencies for testing
              run: pip install -r requirements-test.txt

            - name: Start XVFB
              run: Xvfb :99 &
            
            - name: Install FFMPEG
              uses: FedericoCarboni/setup-ffmpeg@v3
              id: setup-ffmpeg
              with:
                ffmpeg-version: 7.1.1

            - name: Run tests
              run: python -m pytest tests/
              env:
                  DISPLAY: :99

            - name: Upload screenshots (if any)
              uses: actions/upload-artifact@v4
              if: failure()
              with:
                  name: screenshots
                  path: ./*.png

        services:
            app:
                image: ghcr.io/carlosfranzreb/boulders/myclimbz:pr-${{ github.event.number }}
                volumes:
                    - ${{ github.workspace }}/instance:/usr/src/instance
                options: --name app
                ports:
                    - 5000:5000
                credentials:
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}
                env:
                    FLASK_DEBUG: 1
                    DISABLE_LOGIN: 1
                    CLIMBZ_DB_URI: sqlite:///test_100.db
                    PROD: 0
                    RECAPTCHA_PUBLIC_KEY: test
                    RECAPTCHA_PRIVATE_KEY: test
                    MAIL_USERNAME: test@myclimbz.es
                    MAIL_PASSWORD: test
                    UPLOAD_FOLDER: /usr/src/files
