# For this to work, the last commit message must contain the version number in the
# format "Version: x.y.z"

name: "tag"
on:
  push:
    branches:
      - main
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: christophebedard/tag-version-commit@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version_regex: 'Version: ([0-9]+\.[0-9]+\.[0-9]+)'
          version_tag_prefix: "v"
          check_entire_commit_message: true
